# Generated by Django 4.2.6 on 2024-08-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("area_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("department_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("division_name", models.CharField(max_length=100)),
                (
                    "division_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web_ama.department",
                        verbose_name="Department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="process_assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "process_assessment_date",
                    models.DateField(verbose_name="Date Assessed"),
                ),
                ("process_description", models.TextField(verbose_name="Description")),
                (
                    "process_name_c",
                    models.CharField(max_length=100, verbose_name="Comments"),
                ),
                (
                    "process_name_s",
                    models.CharField(max_length=100, verbose_name="Source"),
                ),
                ("process_name_n", models.TextField(verbose_name="Next Steps")),
                ("process_trigger_c", models.TextField(verbose_name="Comments")),
                (
                    "process_trigger_s",
                    models.CharField(max_length=100, verbose_name="Source"),
                ),
                ("process_trigger_n", models.TextField(verbose_name="Next Steps")),
                ("process_tools_c", models.TextField(verbose_name="Comments")),
                (
                    "process_tools_s",
                    models.CharField(max_length=100, verbose_name="Source"),
                ),
                ("process_tools_n", models.TextField(verbose_name="Next Steps")),
                ("process_steps_c", models.TextField(verbose_name="Comments")),
                (
                    "process_steps_s",
                    models.CharField(max_length=100, verbose_name="Source"),
                ),
                ("process_steps_n", models.TextField(verbose_name="Next Steps")),
                ("process_actors_c", models.TextField(verbose_name="Comments")),
                (
                    "process_actors_s",
                    models.CharField(max_length=100, verbose_name="Source"),
                ),
                ("process_actors_n", models.TextField(verbose_name="Next Steps")),
                ("process_objective_c", models.TextField(verbose_name="Comments")),
                (
                    "process_objective_s",
                    models.CharField(max_length=100, verbose_name="Source"),
                ),
                ("process_objective_n", models.TextField(verbose_name="Next Steps")),
                (
                    "process_grade",
                    models.CharField(
                        max_length=3, verbose_name="Grade given by Supervisor"
                    ),
                ),
                ("process_proposal", models.TextField(verbose_name="Recommendations")),
                (
                    "process_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web_ama.area",
                        verbose_name="Area",
                    ),
                ),
                (
                    "process_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web_ama.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "process_division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="web_ama.division",
                        verbose_name="Division",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="area",
            name="area_department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="web_ama.department",
                verbose_name="Department",
            ),
        ),
        migrations.AddField(
            model_name="area",
            name="area_division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="web_ama.division",
                verbose_name="Division",
            ),
        ),
    ]
