# Generated by Django 4.2.6 on 2024-08-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_ama", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="process_assessment",
            name="process_lead",
            field=models.TextField(null=True, verbose_name="Process Lead"),
        ),
        migrations.AddField(
            model_name="process_assessment",
            name="process_status",
            field=models.CharField(
                choices=[
                    ("Deprecated", "Deprecated"),
                    ("On-going", "On-going"),
                    ("Implementing", "Implementing"),
                ],
                default="On-going",
                max_length=255,
            ),
        ),
    ]
