# Generated by Django 4.2.6 on 2024-10-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_ama", "0002_process_assessment_process_lead_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="process_assessment",
            name="process_lead_bk",
            field=models.TextField(null=True, verbose_name="Process Lead Backup"),
        ),
    ]
