# Generated by Django 4.2.6 on 2024-10-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("web_ama", "0005_convert_process_lead_to_foreign_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="process_assessment",
            name="process_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="led_processes",
                to="web_ama.technology_staff",
                verbose_name="Process Lead",
            ),
        ),
    ]
